### PR TITLE
Project Setup

### PR DESCRIPTION
**Pull request by ChaabaneAnas**
## Changes

- Webpack Setup 
- add Basic layout

### CODE REVIEW

**Review by HAMMAS-SALEEM — COMMENTED** [review]
# Invalid Pull Request :red_circle: :traffic_light: :rotating_light:

## Hey @ChaabaneAnas :wave: 

**You have made a great effort on your project :blush: and I can see that but unfortunately I can not proceed with a code review of your pull request due to the following reasons :receipt:**

## 1. 
- [ ] You have submitted this [PR](https://github.com/ChaabaneAnas/Leaderboard-1-/pull/1) first time where you got the review. Please submit the same pull request to make your work consistent :+1:

### Once you implement all the changes you should be ready to submit your project for a review :rocket: :rocket:

Cheers and Happy coding!👏👏👏

### Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @HAMMAS-SALEEM in your question so I can receive the notification. You can reach out to me on slack by searching my name (Hammas Bin Saleem) for any explanation.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ChaabaneAnas** [comment]
Hello @HAMMAS-SALEEM,
The old repo was corrupted
and deleted for this purpose I'm not able to work on it 
anymore

**Comment by enniopo** [comment]
For the next CR: Please review the project as if it was the First Review.

**Review by rloterh — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi Anas,  

Your project is complete, great job! There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Highlights 👍
- Project is setup correctly
- Webpack is correctly configured


<br>
Keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
